# Logging configuration
# Log file name
logFile: blackjack.log
# The level of messages you want logged to the file (DEBUG, INFO, WARNING, ERROR, CRITICAL)
logLevel: DEBUG
logMessageFormat: "%(asctime)s %(levelname)s: %(message)s"

test:
  en:
    sample_test: "sample text"